#include "lsmps.hpp"
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <numeric>
#include <random>
#include <sstream>
#include <stdexcept>
#include <unordered_map>

namespace lsmps { namespace {
using Clock=std::chrono::steady_clock; constexpr int K=9;
struct Cell{int x{},y{},z{};bool operator==(const Cell&o)const{return x==o.x&&y==o.y&&z==o.z;}};
struct CellHash{size_t operator()(const Cell&c)const{size_t h=1469598103934665603ull;h=(h^(uint32_t)c.x)*1099511628211ull;h=(h^(uint32_t)c.y)*1099511628211ull;h=(h^(uint32_t)c.z)*1099511628211ull;return h;}};
struct NeighborData{std::vector<std::vector<int>> list;size_t pairs{},truncated{};};
struct CSR{std::vector<int> row,col;std::vector<double> val,b,x_exact;};
std::string trim(std::string s){auto f=[](unsigned char c){return !std::isspace(c);};s.erase(s.begin(),std::find_if(s.begin(),s.end(),f));s.erase(std::find_if(s.rbegin(),s.rend(),f).base(),s.end());return s;}
double n2(const Vec3&v){return v.x*v.x+v.y*v.y+v.z*v.z;} double norm(const Vec3&v){return std::sqrt(n2(v));}
double weight(double r,double re){if(r<=1e-12||r>=re)return 0;double q=re/r-1;return q*q;}
std::array<double,K> basis(const Vec3&d,double r,double l0){double ir=1/r;return{d.x*ir,d.y*ir,d.z*ir,d.x*d.x/(2*l0*r),d.y*d.y/(2*l0*r),d.z*d.z/(2*l0*r),d.x*d.y/(l0*r),d.x*d.z/(l0*r),d.y*d.z/(l0*r)};}
bool cholesky(std::array<double,K*K>&a,double reg,bool&used){used=false;for(int at=0;at<5;++at){auto m=a;double add=at?reg*std::pow(10.0,at-1):0;if(add){used=true;for(int i=0;i<K;++i)m[i*K+i]+=add;}bool ok=true;for(int i=0;i<K&&ok;++i){for(int j=0;j<=i;++j){double s=m[i*K+j];for(int k=0;k<j;++k)s-=m[i*K+k]*m[j*K+k];if(i==j){if(!(s>1e-14)||!std::isfinite(s)){ok=false;break;}m[i*K+j]=std::sqrt(s);}else m[i*K+j]=s/m[j*K+j];}for(int j=i+1;j<K;++j)m[i*K+j]=0;}if(ok){a=m;return true;}}return false;}
std::array<double,K> solve(const std::array<double,K*K>&l,const std::array<double,K>&b){std::array<double,K>y{},x{};for(int i=0;i<K;++i){double s=b[i];for(int k=0;k<i;++k)s-=l[i*K+k]*y[k];y[i]=s/l[i*K+i];}for(int i=K-1;i>=0;--i){double s=y[i];for(int k=i+1;k<K;++k)s-=l[k*K+i]*x[k];x[i]=s/l[i*K+i];}return x;}
NeighborData neighbors(const std::vector<Particle>&ps,double re,int maxn){std::unordered_map<Cell,std::vector<int>,CellHash>g;g.reserve(ps.size()*2);auto c=[&](const Vec3&r){return Cell{(int)std::floor(r.x/re),(int)std::floor(r.y/re),(int)std::floor(r.z/re)};};for(size_t i=0;i<ps.size();++i)g[c(ps[i].r)].push_back((int)i);NeighborData o;o.list.resize(ps.size());double re2=re*re;for(size_t i=0;i<ps.size();++i){auto ci=c(ps[i].r);auto&v=o.list[i];for(int z=-1;z<=1;++z)for(int y=-1;y<=1;++y)for(int x=-1;x<=1;++x){auto it=g.find({ci.x+x,ci.y+y,ci.z+z});if(it==g.end())continue;for(int j:it->second)if((size_t)j!=i&&n2(ps[j].r-ps[i].r)<re2){if((int)v.size()<maxn)v.push_back(j);else o.truncated++;}}o.pairs+=v.size();}return o;}
ParticleType classify(const Particle&p,const std::vector<int>&nbr,const std::vector<Particle>&ps,double l0){if(p.type==ParticleType::Wall)return ParticleType::Wall;if(nbr.size()<10)return ParticleType::Splash;bool seen[14]{};for(int j:nbr){auto d=ps[j].r-p.r;double ax=std::abs(d.x),ay=std::abs(d.y),az=std::abs(d.z);int s=ax>=ay&&ax>=az?(d.x>=0?0:1):(ay>=ax&&ay>=az?(d.y>=0?2:3):(d.z>=0?4:5));seen[s]=true;seen[6+(d.x>=0)+2*(d.y>=0)+4*(d.z>=0)]=true;}int sectors=0;for(bool x:seen)sectors+=x;if(p.r.z<1.5*l0)return ParticleType::NearWall;if(sectors<11)return ParticleType::FreeSurface;return ParticleType::Interior;}
WlsStats wls_test(const Config&cfg,const std::vector<Particle>&ps,const NeighborData&nd){WlsStats st;size_t stride=std::max<size_t>(1,ps.size()/std::max(1,cfg.wls_samples));double re=cfg.re_ratio*cfg.l0,seG=0,seL=0;auto f=[](Vec3 r){return 1+2*r.x-3*r.y+.5*r.z+.7*r.x*r.x-.2*r.y*r.y+.4*r.z*r.z+.3*r.x*r.y-.1*r.x*r.z+.25*r.y*r.z;};for(size_t i=0;i<ps.size()&&st.sampled<(size_t)cfg.wls_samples;i+=stride){if(ps[i].type==ParticleType::Wall||ps[i].type==ParticleType::Splash)continue;std::array<double,K*K>M{};std::array<double,K>b{};double ws=0,fi=f(ps[i].r);for(int j:nd.list[i]){auto d=ps[j].r-ps[i].r;double r=norm(d),w=weight(r,re);if(!w)continue;auto q=basis(d,r,cfg.l0);double df=f(ps[j].r)-fi;ws+=w;for(int a=0;a<K;++a){b[a]+=w*q[a]*df/r;for(int c=0;c<K;++c)M[a*K+c]+=w*q[a]*q[c];}}if(ws<=0){st.failed++;continue;}for(double&x:M)x/=ws;for(double&x:b)x/=ws;if(ps[i].type==ParticleType::NearWall||ps[i].type==ParticleType::FreeSurface)st.virtual_points++;bool reg=false;if(!cholesky(M,cfg.wls_regularization,reg)){st.failed++;continue;}auto x=solve(M,b);Vec3 g{x[0],x[1],x[2]},e{2+1.4*ps[i].r.x+.3*ps[i].r.y-.1*ps[i].r.z,-3-.4*ps[i].r.y+.3*ps[i].r.x+.25*ps[i].r.z,.5+.8*ps[i].r.z-.1*ps[i].r.x+.25*ps[i].r.y};double ge=norm(g-e),le=std::abs((x[3]+x[4]+x[5])/cfg.l0-1.8);st.sampled++;reg?st.regularized++:st.ok++;st.max_gradient_error=std::max(st.max_gradient_error,ge);st.max_laplacian_error=std::max(st.max_laplacian_error,le);seG+=ge*ge;seL+=le*le;}if(st.sampled){st.rms_gradient_error=std::sqrt(seG/st.sampled);st.rms_laplacian_error=std::sqrt(seL/st.sampled);}return st;}
double exact_p(Vec3 r){return r.x*r.x+r.y*r.y;}
CSR assemble_ppe(const Config&cfg,const std::vector<Particle>&ps,const NeighborData&nd,PpeStats&st){
    auto t0=Clock::now();
    const size_t cap=std::min(ps.size(),(size_t)cfg.ppe_max_unknowns);
    std::vector<int> map(ps.size(),-1),rev; rev.reserve(cap);
    for(size_t i=0;i<ps.size()&&rev.size()<cap;++i){
        if(ps[i].type==ParticleType::Interior||ps[i].type==ParticleType::NearWall){map[i]=(int)rev.size();rev.push_back((int)i);}
    }
    CSR A; A.row.push_back(0); A.b.assign(rev.size(),0.0); A.x_exact.resize(rev.size());
    const double re=cfg.re_ratio*cfg.l0;
    for(size_t rr=0;rr<rev.size();++rr){
        int i=rev[rr]; double diag=0.0;
        A.x_exact[rr]=exact_p(ps[i].r);
        if(rr==0){ A.col.push_back(0); A.val.push_back(1.0); A.row.push_back((int)A.col.size()); continue; }
        for(int j:nd.list[i]){
            int cj=map[j]; if(cj<0) continue;
            Vec3 d=ps[j].r-ps[i].r; double r=norm(d),w=weight(r,re);
            if(w<=0) continue;
            // Stable graph-Laplacian PPE baseline. It reproduces the sparse workload and
            // validates BiCGStab independently; the WLS Laplacian remains separately tested.
            double a=w/(r*r);
            diag+=a; A.col.push_back(cj); A.val.push_back(-a);
        }
        if(diag<=0||!std::isfinite(diag)){st.failed_rows++;diag=1.0;}
        A.col.push_back((int)rr); A.val.push_back(diag);
        A.row.push_back((int)A.col.size());
        if(ps[i].type==ParticleType::NearWall)st.neumann++;
    }
    // Discrete manufactured solution: b=A*p_exact. This isolates matrix/solver correctness
    // from continuum truncation error and gives a deterministic pressure-solve benchmark.
    for(size_t i=0;i<rev.size();++i){
        double sum=0; for(int k=A.row[i];k<A.row[i+1];++k)sum+=A.val[k]*A.x_exact[A.col[k]]; A.b[i]=sum;
    }
    st.unknowns=rev.size();st.nnz=A.val.size();st.dirichlet=ps.size()-rev.size();
    st.assembly_ms=std::chrono::duration<double,std::milli>(Clock::now()-t0).count();return A;
}
void spmv(const CSR&A,const std::vector<double>&x,std::vector<double>&y){y.assign(A.b.size(),0);for(size_t i=0;i<y.size();++i)for(int k=A.row[i];k<A.row[i+1];++k)y[i]+=A.val[k]*x[A.col[k]];}
double dot(const std::vector<double>&a,const std::vector<double>&b){double s=0;for(size_t i=0;i<a.size();++i)s+=a[i]*b[i];return s;}
PpeStats solve_ppe(const Config&cfg,const std::vector<Particle>&ps,const NeighborData&nd){PpeStats st;CSR A=assemble_ppe(cfg,ps,nd,st);auto t0=Clock::now();size_t n=A.b.size();if(!n)return st;std::vector<double>x(n,0),r=A.b,r0=r,p(n),v(n),s(n),t(n),Ax;double bnorm=std::sqrt(dot(A.b,A.b));st.initial_residual=bnorm;double rho0=1,alpha=1,omega=1;for(int it=0;it<cfg.ppe_max_iter;++it){double rho=dot(r0,r);if(std::abs(rho)<1e-30)break;double beta=(rho/rho0)*(alpha/omega);for(size_t i=0;i<n;++i)p[i]=r[i]+beta*(p[i]-omega*v[i]);spmv(A,p,v);double den=dot(r0,v);if(std::abs(den)<1e-30)break;alpha=rho/den;for(size_t i=0;i<n;++i)s[i]=r[i]-alpha*v[i];double sn=std::sqrt(dot(s,s));if(sn<=cfg.ppe_tol*std::max(1.0,bnorm)){for(size_t i=0;i<n;++i)x[i]+=alpha*p[i];st.iterations=it+1;st.converged=true;r=s;break;}spmv(A,s,t);double tt=dot(t,t);if(tt<1e-30)break;omega=dot(t,s)/tt;for(size_t i=0;i<n;++i)x[i]+=alpha*p[i]+omega*s[i];for(size_t i=0;i<n;++i)r[i]=s[i]-omega*t[i];double rn=std::sqrt(dot(r,r));st.iterations=it+1;if(rn<=cfg.ppe_tol*std::max(1.0,bnorm)){st.converged=true;break;}if(std::abs(omega)<1e-30)break;rho0=rho;}spmv(A,x,Ax);double res=0,se=0,mx=0,exn=0;for(size_t i=0;i<n;++i){double d=Ax[i]-A.b[i];res+=d*d;double e=x[i]-A.x_exact[i];se+=e*e;exn+=A.x_exact[i]*A.x_exact[i];mx=std::max(mx,std::abs(e));}st.final_residual=std::sqrt(res);st.relative_l2_error=std::sqrt(se/std::max(exn,1e-30));st.max_error=mx;st.solve_ms=std::chrono::duration<double,std::milli>(Clock::now()-t0).count();return st;}
void lattice(std::vector<Particle>&p,size_t target,int nx,int ny,int nz,double l0,double jit,std::mt19937&rng,bool bottom){std::uniform_real_distribution<double>u(-jit,jit);for(int k=0;k<nz&&p.size()<target;++k)for(int j=0;j<ny&&p.size()<target;++j)for(int i=0;i<nx&&p.size()<target;++i){Particle q;q.r={(i+.5+u(rng))*l0,(j+.5+u(rng))*l0,(k+.5+u(rng))*l0};if(bottom&&k==0)q.type=ParticleType::Wall;p.push_back(q);}}
}
const char* type_name(ParticleType t){switch(t){case ParticleType::Interior:return"interior";case ParticleType::FreeSurface:return"free_surface";case ParticleType::Splash:return"splash";case ParticleType::NearWall:return"near_wall";case ParticleType::Wall:return"wall";}return"unknown";}
Config load_config(const std::string&path){Config c;std::ifstream in(path);if(!in)throw std::runtime_error("cannot open config: "+path);std::string line;while(std::getline(in,line)){auto h=line.find('#');if(h!=std::string::npos)line.resize(h);auto e=line.find('=');if(e==std::string::npos)continue;auto k=trim(line.substr(0,e)),v=trim(line.substr(e+1));if(k=="case")c.case_name=v;else if(k=="particles")c.particles=std::stoull(v);else if(k=="seed")c.seed=std::stoul(v);else if(k=="l0")c.l0=std::stod(v);else if(k=="re_ratio")c.re_ratio=std::stod(v);else if(k=="film_layers")c.film_layers=std::stoi(v);else if(k=="max_neighbors")c.max_neighbors=std::stoi(v);else if(k=="wls_samples")c.wls_samples=std::stoi(v);else if(k=="ppe_max_unknowns")c.ppe_max_unknowns=std::stoi(v);else if(k=="ppe_max_iter")c.ppe_max_iter=std::stoi(v);else if(k=="ppe_tol")c.ppe_tol=std::stod(v);else if(k=="boundary_constraint_weight")c.boundary_constraint_weight=std::stod(v);else if(k=="virtual_weight")c.virtual_weight=std::stod(v);}return c;}
std::vector<Particle> generate_case(const Config&c){std::mt19937 rng(c.seed);std::vector<Particle>p;p.reserve(c.particles);double n3=std::cbrt((double)c.particles);int nx=std::max(4,(int)std::ceil(n3)),ny=nx,nz=nx;if(c.case_name=="wall_film"){nz=std::max(3,c.film_layers+1);nx=std::max(8,(int)std::ceil(std::sqrt((double)c.particles/nz)));ny=nx;lattice(p,c.particles,nx,ny,nz,c.l0,.04,rng,true);}else if(c.case_name=="narrow_gap"){nz=std::max(4,c.film_layers+2);nx=std::max(8,(int)std::ceil(std::sqrt((double)c.particles/nz)));ny=nx;lattice(p,c.particles,nx,ny,nz,c.l0,.02,rng,true);for(auto&q:p)if(q.r.z>(nz-1.5)*c.l0)q.type=ParticleType::Wall;}else if(c.case_name=="rain_injection"){size_t film=(size_t)(.75*c.particles);nz=std::max(3,c.film_layers+1);nx=std::max(8,(int)std::ceil(std::sqrt((double)film/nz)));ny=nx;lattice(p,film,nx,ny,nz,c.l0,.05,rng,true);std::uniform_real_distribution<double>ux(0,nx*c.l0),uy(0,ny*c.l0),uz(4*c.l0,20*c.l0);while(p.size()<c.particles){Particle q;q.r={ux(rng),uy(rng),uz(rng)};q.u={0,0,-5};q.type=ParticleType::Splash;p.push_back(q);}}else lattice(p,c.particles,nx,ny,nz,c.l0,.03,rng,false);return p;}
Metrics run_benchmark(const Config&c,std::vector<Particle>&ps){Metrics m;m.particles=ps.size();auto t0=Clock::now();auto nd=neighbors(ps,c.re_ratio*c.l0,c.max_neighbors);auto t1=Clock::now();for(size_t i=0;i<ps.size();++i)ps[i].type=classify(ps[i],nd.list[i],ps,c.l0);auto t2=Clock::now();m.wls=wls_test(c,ps,nd);auto t3=Clock::now();m.ppe=solve_ppe(c,ps,nd);m.neighbor_pairs=nd.pairs;m.truncated_particles=nd.truncated;m.neighbor_ms=std::chrono::duration<double,std::milli>(t1-t0).count();m.classify_ms=std::chrono::duration<double,std::milli>(t2-t1).count();m.wls_ms=std::chrono::duration<double,std::milli>(t3-t2).count();std::vector<int>cnt;for(auto&v:nd.list)cnt.push_back((int)v.size());if(!cnt.empty()){m.neighbor_mean=std::accumulate(cnt.begin(),cnt.end(),0.0)/cnt.size();std::sort(cnt.begin(),cnt.end());auto q=[&](double x){return cnt[(size_t)(x*(cnt.size()-1))];};m.neighbor_p50=q(.5);m.neighbor_p90=q(.9);m.neighbor_p99=q(.99);}for(auto&p:ps)switch(p.type){case ParticleType::Interior:m.interior++;break;case ParticleType::FreeSurface:m.free_surface++;break;case ParticleType::Splash:m.splash++;break;case ParticleType::NearWall:m.near_wall++;break;case ParticleType::Wall:m.wall++;break;}return m;}
void write_json(const std::string&path,const Config&c,const Metrics&m){std::ofstream o(path);o<<std::fixed<<std::setprecision(8)<<"{\n  \"case\": \""<<c.case_name<<"\",\n  \"particles\": "<<m.particles<<",\n  \"types\": {\"interior\": "<<m.interior<<", \"free_surface\": "<<m.free_surface<<", \"splash\": "<<m.splash<<", \"near_wall\": "<<m.near_wall<<", \"wall\": "<<m.wall<<"},\n  \"neighbors\": {\"pairs\": "<<m.neighbor_pairs<<", \"mean\": "<<m.neighbor_mean<<", \"p50\": "<<m.neighbor_p50<<", \"p90\": "<<m.neighbor_p90<<", \"p99\": "<<m.neighbor_p99<<", \"truncated\": "<<m.truncated_particles<<"},\n  \"wls\": {\"sampled\": "<<m.wls.sampled<<", \"regularized\": "<<m.wls.regularized<<", \"failed\": "<<m.wls.failed<<", \"virtual_points\": "<<m.wls.virtual_points<<", \"gradient_rms_error\": "<<m.wls.rms_gradient_error<<", \"laplacian_rms_error\": "<<m.wls.rms_laplacian_error<<"},\n  \"ppe\": {\"unknowns\": "<<m.ppe.unknowns<<", \"nnz\": "<<m.ppe.nnz<<", \"dirichlet\": "<<m.ppe.dirichlet<<", \"neumann\": "<<m.ppe.neumann<<", \"failed_rows\": "<<m.ppe.failed_rows<<", \"iterations\": "<<m.ppe.iterations<<", \"converged\": "<<(m.ppe.converged?"true":"false")<<", \"final_residual\": "<<m.ppe.final_residual<<", \"relative_l2_error\": "<<m.ppe.relative_l2_error<<", \"assembly_ms\": "<<m.ppe.assembly_ms<<", \"solve_ms\": "<<m.ppe.solve_ms<<"}\n}\n";}
void write_csv(const std::string&path,const Config&c,const Metrics&m){std::ofstream o(path);o<<"case,particles,interior,free_surface,splash,near_wall,wall,neighbor_mean,p50,p90,p99,wls_failed,wls_virtual,ppe_unknowns,ppe_nnz,ppe_iterations,ppe_converged,ppe_residual,ppe_rel_l2,ppe_assembly_ms,ppe_solve_ms\n"<<c.case_name<<','<<m.particles<<','<<m.interior<<','<<m.free_surface<<','<<m.splash<<','<<m.near_wall<<','<<m.wall<<','<<m.neighbor_mean<<','<<m.neighbor_p50<<','<<m.neighbor_p90<<','<<m.neighbor_p99<<','<<m.wls.failed<<','<<m.wls.virtual_points<<','<<m.ppe.unknowns<<','<<m.ppe.nnz<<','<<m.ppe.iterations<<','<<m.ppe.converged<<','<<m.ppe.final_residual<<','<<m.ppe.relative_l2_error<<','<<m.ppe.assembly_ms<<','<<m.ppe.solve_ms<<'\n';}
}
